apiVersion: apps/v1
kind: Deployment
metadata:
  name: prime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prime-service
  template:
      metadata:
          labels:
            app: prime-service
      spec:
        containers:
        - name: prime-service
          image: p466spring2025josephtham.azurecr.io/prime-service:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: postgres-primes-secrets
          resources:
                  requests:
                    memory: "256Mi"
                    cpu: "200m"
                  limits:
                    memory: "512Mi"
                    cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: prime-service
spec:
  selector:
    app: prime-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-primes-secrets
stringData:
  DATASOURCE_PASSWORD: p4662025!
  DATASOURCE_USERNAME: admin2025
  DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/primes